nelmio_api_doc:
    documentation:
        servers:
            - url: localhost:8000
              description: API over HTTP
        info:
            title: DoubletsChurchTools
            description: Example Api for searching and merging doublet datasets
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc.json$) # Accepts routes under /api except /api/doc.json
