version: '3'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_churchtools
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
  php:
    container_name: php
    image: php:8.0-fpm
    ports:
      - '9000:9000'
    volumes:
      - ./code:/code
  nginx:
    container_name: nginx
    image: nginx:latest
    links:
      - php
    ports:
      - '8080:80'
    volumes:
      - ./code:/code
      #- ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  #DB admin console for testing
  adminer:
    image: adminer
    restart: always
    ports:
      - '6543:6543'



volumes:
###> doctrine/doctrine-bundle ###
db-data:
###< doctrine/doctrine-bundle ###
