version: '3'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: testSym
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    #volumes:
      #- ./database/init:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
  php:
    container_name: php
    build:
      context: .
      dockerfile: Docker/php/Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./code:/code
    depends_on:
      - database
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Docker/nginx/Dockerfile
    links:
      - php
    ports:
      - '80:80'
    #volumes:
    depends_on:
      - database
      - php

  #DB admin console for testing
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - database
      - php
      - nginx



