version: '2.4'

services:
  database:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: testSym
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  php:
    container_name: php
    build:
      context: .
      dockerfile: Docker/php/Dockerfile
    ports:
      - '9000:9000'
    command: sh -c "php bin/console doctrine:database:create --if-not-exists && php bin/console doctrine:migrations:diff -n --allow-empty-diff  && php bin/console doctrine:migrations:migrate -n --allow-no-migration && php bin/console doctrine:database:import -n ./Docker/database/init/init.sql && php-fpm"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DBS_DOMAIN_NAME=mysql_docker
    links:
      - "database:mysql_docker"
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Docker/nginx/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - database
      - php

  #DB admin console for testing
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - database
      - php
      - nginx



